export { default as About } from './About';

export { default as How } from './How';
export { default as Necrology } from './Necrology';
export { default as Error } from './Error';
export { default as Home } from './Home';
export { default as HomeLayout } from './HomeLayout';
export { default as Landing } from './Landing';
export { default as Login } from './Login';

export { default as Team } from './Team';
export { default as Register } from './Register';
export { default as Bylaws } from './Bylaws';
export { default as Contact } from './Contact';
export { default as ForgotPassword } from './ForgotPassword';
export { default as ResetPassword } from './ResetPassword';
export { default as DashboardLayout } from './DashboardLayout';
export { default as AddMembers } from './AddMembers';
export { default as Announcement } from './Announcement';
export { default as AllMembers } from './AllMembers';
export { default as Profile } from './Profile';
export { default as Stats } from './Stats';
export { default as Admin } from './Admin';
export { default as EditMember } from './EditMember';
export { default as AdminAllMembers } from './AdminAllMembers';
// export { default as AdminAllDeceased } from './AdminAllDeceased';
export { default as AdminEditMember } from './AdminEditMember';
// export { default as AdminEditDeceased } from './AdminEditDeceased';
export { default as DeathAnnouncement } from './DeathAnnouncement';
export { default as SingleNecrology } from './SingleNecrology';
export { default as LegalNotice } from './LegalNotice';
export { default as PrivacyPolicy } from './PrivacyPolicy';
export { default as TermOfService } from './TermOfService';
