const FallenMembers = [
  {
    index: 1,
    matriculation: 'BUANSAGIO33',
    firstName: 'ODETTE SANDRA',
    lastName: 'MINKAM WAFFO',
    registrationDate: '25-SEP-2019',
    dateOfDeath: '1-JUL-2023',
    publicationDate: '6-FEB-2024',
  },
  {
    index: 2,
    matriculation: 'ASANNA234599',
    firstName: 'Manfred',
    lastName: 'MANDIN ATOGA',
    registrationDate: '3-MAR-2022',
    dateOfDeath: '3-MAR-2024',
    publicationDate: '6-FEB-2024',
  },
  {
    index: 3,
    matriculation: 'ASANNA234578',
    firstName: 'Manfred',
    lastName: 'MANDIN ATOGA',
    registrationDate: '3-MAR-2022',
    dateOfDeath: '3-MAR-2024',
    publicationDate: '6-FEB-2024',
  },
  {
    index: 4,
    matriculation: 'ASANNA234500',
    firstName: 'Manfred',
    lastName: 'MANDIN ATOGA',
    registrationDate: '3-MAR-2022',
    dateOfDeath: '3-MAR-2024',
    publicationDate: '6-FEB-2024',
  },
  {
    index: 5,
    matriculation: 'ASANNA234576',
    firstName: 'Manfred',
    lastName: 'MANDIN ATOGA',
    registrationDate: '3-MAR-2022',
    dateOfDeath: '3-MAR-2024',
    publicationDate: '6-FEB-2024',
  },
  {
    index: 6,
    matriculation: 'ASANNA234567',
    firstName: 'Manfred',
    lastName: 'MANDIN ATOGA',
    registrationDate: '3-MAR-2022',
    dateOfDeath: '3-MAR-2024',
    publicationDate: '6-FEB-2024',
  },
  {
    index: 7,
    matriculation: 'ASANNA234509',
    firstName: 'Manfred',
    lastName: 'MANDIN ATOGA',
    registrationDate: '3-MAR-2022',
    dateOfDeath: '3-MAR-2024',
    publicationDate: '6-FEB-2024',
  },
  {
    index: 8,
    matriculation: 'ASANNA234554',
    firstName: 'Manfred',
    lastName: 'MANDIN ATOGA',
    registrationDate: '3-MAR-2022',
    dateOfDeath: '3-MAR-2024',
    publicationDate: '6-FEB-2024',
  },
];
